language: R
sudo: false
cache: packages

before_install:
  - R -e 'install.packages("devtools")'

r:
  - release
  - devel

notifications:
  email: false

r_packages:
  - covr

after_success:
- Rscript -e 'library(covr); codecov()'

