language: R
sudo: false
cache: packages

r:
  - release
  - devel

notifications:
  email: false

before_install:
    - R -e 'install.packages("devtools")'

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
