language: R
sudo: false
cache: packages
dist: xenial

before_install:
    - sudo apt-get install --yes udunits-bin libproj-dev libgeos-dev libgdal-dev libgdal1-dev libudunits2-dev
    - R -e 'source("https://install-github.me/r-lib/remotes")'

env:
  global:
  - R_CHECK_ARGS="--timings"

notifications:
  email: false

r_packages:
  - devtools
  - ggplot2
  - covr
  - pdp
  - dplyr
  - mgcv
  - magrittr
  - purrr
  - tidyr
  - pROC

after_success:
  - Rscript -e 'library(covr); codecov()'
