language: R
sudo: false
use_devtools: false

r:
  - release

notifications:
  email: false

before_install:
  - Rscript -e 'install.packages(c("devtools"));if (!all(c("devtools") %in% installed.packages())) { q(status = 1, save = "no")}'
