language: R
sudo: false
cache: packages
warnings_are_errors: false

r:
  - release
  - devel

apt_packages:
  - libudunits2-dev
  - libgdal1-dev
  - gdal-bin
  - libproj-dev
  - proj-data
  - proj-bin
  - libgeos-dev
 
notifications:
  email: false

r_packages:
  - covr

after_success:
- Rscript -e 'library(covr); codecov()'

