language: R
sudo: false
cache: packages

r:
  - release
  - devel

apt_packages:
  - libudunits2-dev
 
notifications:
  email: false

r_packages:
  - covr

after_success:
- Rscript -e 'library(covr); codecov()'

