language: R
sudo: false
cache: packages

r:
  - release
  - devel

notifications:
  email: false

before_install: R -e 'source("https://install-github.me/r-lib/remotes")'

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
